module.exports.LOG_MODULES = {
  AUTHENTICATION: 'AUTHENTICATION',
  USER_MANAGEMENT: 'USER_MANAGEMENT',
  STUDY_MANAGEMENT: 'STUDY_MANAGEMENT',
  SITE_MANAGEMENT: 'SITE_MANAGEMENT',
  PARTICIPANT_MANAGEMENT: 'PARTICIPANT_MANAGEMENT',
  VISIT_MANAGEMENT: 'VISIT_MANAGEMENT',
  FORM_MANAGEMENT: 'FORM_MANAGEMENT',
  DATA_ENTRY: 'DATA_ENTRY',
  QUERY_MANAGEMENT: 'QUERY_MANAGEMENT',
  DOCUMENT_MANAGEMENT: 'DOCUMENT_MANAGEMENT',
  MONITORING: 'MONITORING',
  NOTIFICATIONS: 'NOTIFICATIONS',
  DASHBOARD: 'DASHBOARD',
  AUDIT_TRAIL: 'AUDIT_TRAIL',
  SETTINGS: 'SETTINGS',
  ROLE_PERMISSION: 'ROLE_PERMISSION',
  SYSTEM: 'SYSTEM'
};